### ISSUE TITLE
KeyError: 'snpid'

### ISSUE THREAD

**Issue by Xuemin-Wang** [JonJala/mtag#103]
Dear all,

mtag keep complaining the above error. It looks like there was a problem when merging the sumstats because of unrecognised 'snpid' header. However, this column was changed to 'SNP' as indicated in the source code, as shown in "Interpreting column names".

Does anyone have a clue to fix this?

thanks,

Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
SNPID:  Variant ID (e.g., rs number)
N:      Sample size
A1:     a1, interpreted as ref allele for signed sumstat.
PVAL:   p-Value
FRQ:    Allele frequency
A2:     a2, interpreted as non-ref allele for signed sumstat.
Z:      Directional summary statistic as specified by --signed-sumstats.
SE:     Standard errors of BETA coefficients

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Read 9227369 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 39835 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 591448 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
8596086 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (8596086 SNPs remain).
Removed 0 SNPs with N < 0.0 (8596086 SNPs remain).
Median value of SIGNED_SUMSTAT was -0.000239913920699, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 1.134
Lambda GC = 1.107
Max chi^2 = 144.361
486 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Thu Aug  6 00:01:04 2020
Total time elapsed: 1.0m:57.22s
'snpid'
Traceback (most recent call last):
  File "/software/mtag/mtag-20190826/mtag.py", line 1567, in <module>
    mtag(args)
  File "/software/mtag/mtag-20190826/mtag.py", line 1336, in mtag
    DATA_U, DATA, args = load_and_merge_data(args)
  File "/software/mtag/mtag-20190826/mtag.py", line 269, in load_and_merge_data
    GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
  File "/software/mtag/mtag-20190826/mtag.py", line 163, in _perform_munge
    GWAS_df = GWAS_df.merge(munged_results, how='inner',left_on =args.snp_name,right_on='SNP',suffixes=('','_ss'))
  File "/software/python/Python-2.7.13/lib/python2.7/site-packages/pandas/core/frame.py", line 6379, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "/software/python/Python-2.7.13/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 60, in merge
    validate=validate)
  File "/software/python/Python-2.7.13/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 550, in __init__
    self.join_names) = self._get_merge_keys()
  File "/software/python/Python-2.7.13/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 870, in _get_merge_keys
    lk, stacklevel=stacklevel))
  File "/software/python/Python-2.7.13/lib/python2.7/site-packages/pandas/core/generic.py", line 1379, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'snpid'
Analysis terminated from error at Thu Aug  6 00:01:04 2020
Total time elapsed: 2.0m:18.3s

**Comment by paturley** [comment]
Hello. I've been trying to diagnose this problem, but have not yet been able to sort through what might be going wrong given the excerpt of the log file you sent. Are you perhaps able to send the complete log file?

**Comment by Xuemin-Wang** [comment]
[allEC_heartattack.log](https://github.com/JonJala/mtag/files/5031460/allEC_heartattack.log)
Hi Patrick,

Thanks for your responsiveness.

Please find attached the complete log file.

Regards,
xuemin

**Comment by Xuemin-Wang** [comment]
Here are the 1st two lines of the sumstats. It might help with the diagnosis.

Regards,
SNPID   POS     CHRM    OA_INFO FRQ     A1      A2      BETA    SE      PVAL    Z       N_original      N
rs6602381       10000018        10      0.991   0.4285835       G       A       0.00463719      0.01541699999                                9999997 0.763579        0.3007841992605565      121885  8589.779895626873

**Comment by paturley** [comment]
Hello,

It looks like you have more entries in the first line of your data than
there are entries in the header. You may need to do a more careful QC
before you can pass the data into MTAG.

**Comment by Xuemin-Wang** [comment]
There are 13 columns. The 1st line of data was not displayed properly due to incorrect separation when my screen was not maximised. Below is the correct one.

SNPID   POS     CHRM    OA_INFO FRQ     A1      A2      BETA    SE      PVAL    Z       N_original      N
rs6602381       10000018        10      0.991   0.4285835       G       A       0.00463719      0.015416999999999997    0.763579        0.3007841992605565      121885  8589.779895626873

**Comment by paturley** [comment]
Ah, ok. This is more sensible. I'll look at your log and see if I can
recommend anything. Have you been able to successfully run MTAG on any
other data sets or is this the only one you have tried?

**Comment by Xuemin-Wang** [comment]
it was okay previously. However, it started to have this issue when I calculated the effective N because this trait is of binary (case/control). The other things I did were converting headers to upper cases and changing the names of POS and CHRM (required by another analysis I had been running). I believe POS and CHRM are not required for mtag.

**Comment by Xuemin-Wang** [comment]
I tried several other sumstats, which were successfully run with mtag, but was not successful this time. That's weird. I'll ask our hpc admin if they made any changes to mtag recently.

**Comment by paturley** [comment]
I know that MTAG sometimes has a hard time parsing the header names. Maybe
try removing any but the required columns?

**Comment by Xuemin-Wang** [comment]
hmmm. tried the sumstats with required columns only (i.e. snpid, frq, a1, a2, p, z, n), but got the same error.

**Comment by paturley** [comment]
Hi,

From your log file, it looks like you are using the beta-SE option. Do you
get the same error when you use the default Z-N option?

Also, in the log file, it looks like you use a different name for your
SNPID column than matches what you give as the first line of your sumstat
file. Don't think that is actually the source of the problem, I was
confused by that.

Best,
Patrick

**Comment by Xuemin-Wang** [comment]
Hi Patrick,

Thanks for your comments. I got the same error with default z-n option, so I tested with --use_beta_se. I could not figure out what might cause the issue after investigating for one day, so in the end I re-formatted all the files. And that solved the problem.

Many thanks,
(other) patrick

**Comment by paturley** [comment]
Hi Patrick,

Hmm. Still a bit curious, but I'm glad you got it to work.

**Comment by Xuemin-Wang** [comment]
Very curious indeed.
