### ISSUE TITLE
KeyError: 'A10' &  jj = (frq <= 0) | (frq => 1) ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pjordab** [JonJala/mtag#106]
Dear authors and users,

Could you help me with the following?

When doing:
**~/projects/def-rtadros/tools/mtag/mtag.py --sumstats file1.txt,file2.txt,file3.txt --out ./mtag_metaformat --n_min 0.0 --force --meta_format --stream_stdout**

I get the following **error:**
Mean chi^2 of SNPs used to estimate Omega is low for some SNPsMTAG may not perform well in this situation.
Beginning estimation of Omega ...
Using GMM estimator of Omega ..
Checking for positive definiteness ..
matrix is not positive definite, performing adjustment..
Completed in 11 iterations
Completed estimation of Omega ...
There are 3166887 SNPs present in Traits [0 6 8]
Beginning MTAG calculations...
 ... Completed MTAG calculations.
There are 28763 SNPs present in Traits [ 0  1  2  5  6  7  8  9 10]
'A10'
Traceback (most recent call last):
  File "/home/pjordab/projects/def-rtadros/tools/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/home/pjordab/projects/def-rtadros/tools/mtag/mtag.py", line 1410, in mtag
    Zs, Ns, Fs, resid_cols, _, N_raw = extract_gwas_sumstats(snp_df, args, tl)
  File "/home/pjordab/projects/def-rtadros/tools/mtag/mtag.py", line 604, in extract_gwas_sumstats
    results_template.loc[:,col] = DATA[col+str(t0[0])]
  File "/project/6005813/tools/Python_ENV/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/project/6005813/tools/Python_ENV/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
**KeyError: 'A10'**
Analysis terminated from error at Tue Aug 18 15:25:05 2020
Total time elapsed: 1.0h:50.0m:3.14s

I used the same sumstats to do the analysis without the –meta_format option and it worked. 

Because I want the results also with –meta_format I updated mtag.py  yesterday doing ‘git pull’:

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/omeed-maghzian/mtag
   841edf1..1fbe6aa  master     -> origin/master
Updating 841edf1..1fbe6aa
Fast-forward
 mtag_munge.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

After, I runned MTAG again and I got the following error:

Traceback (most recent call last):
  File "/home/pjordab/projects/def-rtadros/tools/mtag/mtag.py", line 22, in <module>
    import mtag_munge as munge_sumstats
  File "/project/6005813/tools/mtag/mtag_munge.py", line 351
    **jj = (frq <= 0) | (frq => 1)
                           ^
SyntaxError: invalid syntax**

I modified my sumstats and I excluded all these values from the sumstats. ‘<=0’,’>=1’ and ‘==NA’.

My files look like that:

snpid chr bpos a1 a2 freq z pval n
rs10 7 92383888 A C 0.0571 0.55865678150894 0.5764 40407
rs1000000 12 126890980 A G 0.2214 0.00509554140127389 0.9963 40407
rs10000010 4 21618674 T C 0.4975 0.678955453149002 0.4976 40407
rs10000012 4 1357325 C G 0.8635 -0.419254658385093 0.6746 40407
rs10000013 4 37225069 A C 0.7733 -0.324358974358974 0.7453 40407

I’ve checked the files using  awk '$6<0', awk '$6==0', awk '$6>1' and awk '$6==1', and the values are correct.

I runned again mtag:
~/projects/def-rtadros/tools/mtag/mtag.py --sumstats file1.txt,file2.txt,file3.txt --n_min 0.0 --force --meta_format --stream_stdout

And I get the same **error:**
    **jj = (frq <= 0) | (frq => 1)
                           ^
SyntaxError: invalid syntax**

Do you know which could be the issue?

Many thanks in advance! 

Paloma

**Comment by paturley** [comment]
Hi Paloma,

We recently updated the MTAG software to omit SNPs with a maf==0 or maf==1,
but it looks like there was a typo in our code. (We accidentally used
frq=>1 instead of frq>=1. Whoops.)

We have fixed this problem, so if you pull the repo again, it will
hopefully work for you.

Thanks for bringing this to our attention!

Best,
Patrick

**Comment by pjordab** [comment]
The frq issue is solved after the update, many thanks!
