### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gianolga** [JonJala/mtag#109]
Hello, 

I have installed the mtag using Python 2.7.16. However when I run the "./mtag.py -h" following the instructions I'm getting the following error: 

  File "/SAN/ugi/ukhls/bin/mtag/mtag.py", line 22, in <module>
    import mtag_munge as munge_sumstats
  File "/SAN/ugi/ukhls/bin/mtag/mtag_munge.py", line 351
    jj = (frq <= 0) | (frq => 1)
                           ^
SyntaxError: invalid syntax

Could you please give me any suggestions to sort this out? Many thanks!

**Comment by paturley** [comment]
Hello. We were notified of and resolved this bug a few days ago. If you
pull the repo again, it should work fine.

Best,
Patrick

**Comment by gianolga** [comment]
That worked! Many thanks for the very quickly reply!
