### ISSUE TITLE
MTAG estimated sample size for each SNP

### ISSUE THREAD

**Issue by FEIFEI502** [JonJala/mtag#114]
Hi,

Thanks for the wonderful work. 

I plan to use MTAG summary statistics to generate PRS model, which needs the sample size for each SNP.
I wonder whether there is a proper way to estimate the sample size for each SNP after MTAG.
If there are two traits, can I multiple the sample size of trait 1 with the ratio (chi2MTAG, mean-1)/(chi2GWAS, mean-1) to each SNP no matter what is sample size of trait 2? 
Many appreciate that you have any suggestions to have a better estimation of each SNP sample size. 

Best wishes,
Feifei

**Comment by paturley** [comment]
I think that sounds like a reasonable approximation to me. That is what the
software uses for the "GWAS equivalent N" that is reported in the log file.

**Comment by FEIFEI502** [comment]
Thanks for your quick reply!
