### ISSUE TITLE
single trait mtag maxFDR 

### ISSUE THREAD

**Issue by arkyl** [JonJala/mtag#124]
Hi,

We are running mtag on multiple traits and have a maxFDR of ~0.7 on the trait of interest.  We are more interested about how the mtag maxFDR compared with the original gwas in the trait of interest. So we run mtag on this single trait and got a maxFDR of ~0.66. Since the multi-trait maxFDR 0.7 is not that different from the single-trait maxFDR 0.66, we were quite happy about the results.

I would like to confirm that mtag is ok on single trait. I think sometimes ppl are more interested in knowing how the maxFDR changes compared with the original gwas, instead of the absolute maxFDR value.

Thanks much,
Yue

**Comment by paturley** [comment]
Hello Yue,

I don't know of any reason why a single trait maxFDR would be invalid and I
can see why changes in maxFDR would be a useful benchmark.

Best,
Patrick

**Comment by arkyl** [comment]
Thanks much. please close the thread.
