### ISSUE TITLE
KeyError: 'snpid'; KeyError: 'beta'

### ISSUE THREAD

**Issue by r-lyeeh** [JonJala/mtag#132]
Hello everyone, I'm running MTAG on 3 traits, and it gets stuck. I try to debug using only one trait,

There is a key error like this:
`python ~/program/mtag/mtag.py --sumstats CAD.t1 --out ./Multitrait --use_beta_se --n_min 0.0 --stream_stdout &`

```
Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Read 7619677 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 1529 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
7618148 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (7618148 SNPs remain).
Removed 0 SNPs with N < 0.0 (7618148 SNPs remain).
Median value of SIGNED_SUMSTAT was -0.000274, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 1.075
Lambda GC = 1.009
Max chi^2 = 443.1
2087 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Fri May  7 13:00:07 2021
Total time elapsed: 2.0m:1.2s
'snpid'
Traceback (most recent call last):
  File "/home/pang/program/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/home/pang/program/mtag/mtag.py", line 1336, in mtag
    DATA_U, DATA, args = load_and_merge_data(args)
  File "/home/pang/program/mtag/mtag.py", line 269, in load_and_merge_data
    GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
  File "/home/pang/program/mtag/mtag.py", line 163, in _perform_munge
    GWAS_df = GWAS_df.merge(munged_results, how='inner',left_on =args.snp_name,right_on='SNP',suffixes=('','_ss'))
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/frame.py", line 6868, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 47, in merge
    validate=validate)
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 529, in __init__
    self.join_names) = self._get_merge_keys()
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 846, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/generic.py", line 1706, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'snpid'
Analysis terminated from error at Fri May  7 13:00:07 2021
Total time elapsed: 2.0m:23.48s

```
If I use SNPs P<5E-4 and changed the column name to "snpid", things get better but a new key error appears.
`python ~/program/mtag/mtag.py --sumstats CAD.t2 --out ./Multitrait --use_beta_se --n_min 0.0 --stream_stdout &`

```
Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Read 19688 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
19688 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (19688 SNPs remain).
Removed 0 SNPs with N < 0.0 (19688 SNPs remain).
Median value of SIGNED_SUMSTAT was 0.0343095, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 19.994
Lambda GC = 33.712
Max chi^2 = 443.1
2087 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Fri May  7 12:57:33 2021
Total time elapsed: 0.14s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 1 complete. SNPs remaining:	 19688
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

'beta'
Traceback (most recent call last):
  File "/home/pang/program/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/home/pang/program/mtag/mtag.py", line 1336, in mtag
    DATA_U, DATA, args = load_and_merge_data(args)
  File "/home/pang/program/mtag/mtag.py", line 273, in load_and_merge_data
    GWAS_d[p]['Z'] = GWAS_d[p][args.beta_name] / GWAS_d[p][args.se_name]
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/pang/program/miniconda3/envs/mtag/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'beta'
Analysis terminated from error at Fri May  7 12:57:33 2021
Total time elapsed: 0.26s
```

Are there any suggestions on how could I get rid of it?
Thanks a lot!

**Comment by JonJala** [comment]
It looks like it might just be a case of MTAG not finding the right columns / them not being labeled uniformly.  If you use "mtag.py -h" to see the help screen / flag options, some of them are:

'''
Column names of input files:
  These options manually pass the names of the relevant summary statistics
  columns used by MTAG. It is recommended to pass these names because only
  narrow searches for these columns are performed in the default cases.
  Moreover, it is necessary that these input files be readable by ldsc's
  munge_sumstats command.

  **--snp_name SNP_NAME   Name of the single column that provides the unique
                        identifier for SNPs in the GWAS summary statistics
                        across all GWAS results. Default is "snpid". This the
                        index that will be used to merge the GWAS summary
                        statistics. Any SNP lists passed to ---include or
                        --exclude should also contain the same name.**
  --z_name Z_NAME       The common name of the column of Z scores across all
                        input files. Default is the lowercase letter z.
  **--beta_name BETA_NAME
                        The common name of the column of beta coefficients
                        (effect sizes) across all input files. Must be
                        specified with se. If specified, it will override the
                        z-score column.**
'''

You don't necessarily have to rename your SNP column to \"snpid\" if you just use the --snp\_name flag (unless your files all have different names), but if you want to rename it, that also works.  Ditto for the beta column.

**Comment by r-lyeeh** [comment]
> It looks like it might just be a case of MTAG not finding the right columns / them not being labeled uniformly. If you use "mtag.py -h" to see the help screen / flag options, some of them are:
> 
> '''
> Column names of input files:
> These options manually pass the names of the relevant summary statistics
> columns used by MTAG. It is recommended to pass these names because only
> narrow searches for these columns are performed in the default cases.
> Moreover, it is necessary that these input files be readable by ldsc's
> munge_sumstats command.
> 
> **--snp_name SNP_NAME Name of the single column that provides the unique identifier for SNPs in the GWAS summary statistics across all GWAS results. Default is "snpid". This the index that will be used to merge the GWAS summary statistics. Any SNP lists passed to ---include or --exclude should also contain the same name.**
> --z_name Z_NAME The common name of the column of Z scores across all
> input files. Default is the lowercase letter z.
> **--beta_name BETA_NAME The common name of the column of beta coefficients (effect sizes) across all input files. Must be specified with se. If specified, it will override the z-score column.**
> '''
> 
> You don't necessarily have to rename your SNP column to "snpid" if you just use the --snp_name flag (unless your files all have different names), but if you want to rename it, that also works. Ditto for the beta column.

Thanks! I fixed this problem according to your suggestion.
