### ISSUE TITLE
Non-model species MTAG analysis

### ISSUE THREAD

**Issue by xiaofeiyu1992** [JonJala/mtag#134]
Hi all, 

I am trying to run MTAG with three correlated traits in Nile tilapia. When I did a run with the human test dataset, it worked well. But, it returns me an error like "cannot convert float NaN to integer", when I did not provide an existing rs ID of human. 

Therefore, I am wondering is it possible to apply MTAG in other non-model species? If so, how can I apply those SNPs without standard rsID from the multiply GWAS result?

Please feel free to comment.

Best Regards,
Xiaofei

**Comment by paturley** [comment]
Hi Xiaofei,

Can you supply the complete log file? That will be easier to help us point
you in the right direction.

Patrick

**Comment by xiaofeiyu1992** [comment]
Hi Patrick,

Thanks for your active response again. 
The error is different as described previously. But you can check it below:

Calling ./mtag.py \
--force  \
--stream-stdout  \
--n-min 0.0 \
--use-beta-se  \
--sumstats mtag_input_DGC.txt,mtag_input_harw.txt \
--out ./growth_repeat1

Beginning MTAG analysis...
MTAG will use the provided BETA/SE columns for analyses.
Read in Trait 1 summary statistics (51438 SNPs) from mtag_input_DGC.txt ...
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
snpid:  Variant ID (e.g., rs number)
n:      Sample size
a1:     a1, interpreted as ref allele for signed sumstat.
pval:   p-Value
beta:   Directional summary statistic as specified by --signed-sumstats.
a2:     a2, interpreted as non-ref allele for signed sumstat.
se:     Standard errors of BETA coefficients

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Read 51438 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
51438 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (51438 SNPs remain).
Removed 0 SNPs with N < 0.0 (51438 SNPs remain).
geaMedian value of SIGNED_SUMSTAT was 9.12e-05, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 0.996
WARNING: mean chi^2 may be too small.
Lambda GC = 0.991
Max chi^2 = 20.985
0 Genome-wide significant SNPs (some may have been removed by filtering).

Total time elapsed: 0.65s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 1 complete. SNPs remaining:     51438
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

nWarning: The mean chi2 statistic of trait 1 is less 1.02 - MTAG estimates may be unstable.
Read in Trait 2 summary statistics (51438 SNPs) from mtag_input_harw.txt ...
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
snpid:  Variant ID (e.g., rs number)
n:      Sample size
a1:     a1, interpreted as ref allele for signed sumstat.
pval:   p-Value
beta:   Directional summary statistic as specified by --signed-sumstats.
a2:     a2, interpreted as non-ref allele for signed sumstat.
se:     Standard errors of BETA coefficients

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Read 51438 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
51438 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (51438 SNPs remain).
Removed 0 SNPs with N < 0.0 (51438 SNPs remain).
Median value of SIGNED_SUMSTAT was -0.000205, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 0.998
WARNING: mean chi^2 may be too small.
Lambda GC = 1.009
Max chi^2 = 21.14
0 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Sun Jun 20 22:17:43 2021
Total time elapsed: 0.66s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 2 complete. SNPs remaining:     51438
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Warning: The mean chi2 statistic of trait 2 is less 1.02 - MTAG estimates may be unstable.
Dropped 851 SNPs due to strand ambiguity, 50587 SNPs remain in intersection after merging trait1
Dropped 0 SNPs due to strand ambiguity, 50587 SNPs remain in intersection after merging trait2
... Merge of GWAS summary statistics complete. Number of SNPs:   50587
Using 50587 SNPs to estimate Omega (0 SNPs excluded due to strand ambiguity)
Estimating sigma..
After merging with reference panel LD, 0 SNPs remain.
Traceback (most recent call last):
  File "./mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "./mtag/mtag.py", line 1351, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "./mtag/mtag.py", line 468, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/lustre/backup/WUR/ABGC/yu051/chapter3/02_analyses/mtag/mtag/ldsc_mod/ldscore/sumstats.py", line 423, in estimate_rg
    M_annot, w_ld_cname, ref_ld_cnames, sumstats, _ = _read_ld_sumstats(args, log, None, alleles=True, dropna=True,sumstats=p1)
  File "/lustre/backup/WUR/ABGC/yu051/chapter3/02_analyses/mtag/mtag/ldsc_mod/ldscore/sumstats.py", line 251, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/lustre/backup/WUR/ABGC/yu051/chapter3/02_analyses/mtag/mtag/ldsc_mod/ldscore/sumstats.py", line 236, in _merge_and_log
    raise ValueError(msg.format(N=len(sumstats), F=noun))
ValueError: After merging with reference panel LD, 0 SNPs remain.
Total time elapsed: 9.6s

**Comment by paturley** [comment]
What are you using as your LD scores in your analysis? It looks like there
is zero overlap between your summary statistics and your LD reference panel.

**Comment by xiaofeiyu1992** [comment]
Hi paturley, 

What you pointed out is right. Actually, I used the default LD panel which computed from 1000 Genome project. However, I am not so clear with the prepared files  ldscore.gz and M_5_50 files for  --ld_re_panel. The meaning of L2 column in  ldscore.gz and the number meaning in 10.l2.M_5_50 file. How can I prepare that for non-human species?

Best,
Xiaofei

**Comment by paturley** [comment]
You will need to create LD scores for your non-human species. My only experience is with human applications of MTAG and LDSC, so I'm afraid I'm not going to know all of the intricacies of non-human data, but you might start looking at the LD score tutorial: https://github.com/bulik/ldsc/wiki/LD-Score-Estimation-Tutorial

You might also check issue #28 which was also trying to adapt MTAG to work with a non-human species.

**Comment by xiaofeiyu1992** [comment]
Hi paturley, 

Thanks for your shared tips. I think it works well with my own species now! I am going to close the comment. 

Have a nice day,
Xiaofei
