### ISSUE TITLE
Adding traits to an already existing MTAG summary statistic

### ISSUE THREAD

**Issue by corunesa** [JonJala/mtag#139]
Hello!
I would like to know how reliable it is to perform an MTAG of a summary statistics which is already an MTAG of two traits. I mean, I am interested in trait A, and there is an article that gets significant snp with an MTAG with trait A and B. Now I want to use this summary to add two new traits, C and D. Is this possible or is it better to redo a new MTAG starting from the separate data A, B, C and D?
Thank you very much in advance!

**Comment by paturley** [comment]
Hello,

I can't think of why you couldn't combine MTAG summary statistics using
MTAG. The only reason I think it could be problematic is that it might be
tricky to explain your research design in your methods section. If the
original GWAS summary statistics aren't available, however, I think you
would likely be fine using the MTAG summary statistics.

Patrick

**Comment by corunesa** [comment]
Thank you very much for your prompt response. Yes our problem is that the original GWAS is not available, just the MTAG summary. 
Thank you very much again for your help.
