### ISSUE TITLE
Suitability of MTAG for meta-analysis of identical measures of same trait, but with large sample overlap

### ISSUE THREAD

**Issue by lpgilchrist** [JonJala/mtag#167]
Hi,

I currently have GWAS outputs for two large samples measured on the same trait using the same measurement scale. I would like to combine these in a meta-analysis and am interested in using MTAG as I understand that MTAG is robust against sample overlap even when the overlap is large (which in this case it is). 

My questions are:

1. Whether it makes sense to use MTAG in this way, as these are not multiple measures of the same trait but the same measure of the same trait? My plan would likely use --perfect_gencov and --equal_h2, but be taking advantage of MTAGs robustness against sample overlap.
2. Whether output from such a meta-analysis in MTAG is suitable for combination in METAL with other GWAS samples, in this case all non-overlapping with the MTAG samples?

Thanks in advance for all your help,

Lachlan

**Comment by paturley** [comment]
Yes. MTAG should be able to handle this just fine. And you should be able
to use MTAG output for meta-analysis in METAL if you'd like.

Best,
Patrick

**Comment by lpgilchrist** [comment]
Hi Patrick, 

Great! Thanks for getting back to me so quickly with answers to these questions! 

I will close the issue now and reopen if I have any related questions down the line.

Kind regards,

Lachlan
