### ISSUE TITLE
Estimated genetic correlation and mtag output 

### ISSUE THREAD

**Issue by ChloePittman** [JonJala/mtag#173]
Hello,
 
As I have understood, "The first step in MTAG is to estimate the
genetic correlation between the pairs of included traits and it uses that
estimate in order to combine the summary statistics." (issue #90).
Are the estimated pair-wise correlations returned somewhere by MTAG or do we have to run it separately? 

Also on the following output as an example:
- what are the two correlations are the end corresponding to? 
- what is the difference between the chi^2 written in the Metadata sections and the one in the Summary of MTAG results? (for instance for Trait 1 the first is 1.506 and the second 1.523).

Thank you in advance!
Best,
Chloé

<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<>
<> MTAG: Multi-trait Analysis of GWAS
<> Version: 1.0.8
<> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
<> Harvard University Department of Economics / Broad Institute of MIT and Harvard
<> GNU General Public License v3
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<> Note:  It is recommended to run your own QC on the input before using this program.
<> Software-related correspondence: jjala.ssgac@gmail.com
<> All other correspondence: paturley@broadinstitute.org
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Calling ./mtag.py \
--stream-stdout  \
--n-min 0.0 \
--sumstats .\preprocessed sumstats MTAG\hypothyroidism_preproc_sumsats.txt,.\preprocessed sumstats MTAG\anemia_preproc_sumsats.txt \
--fdr

Beginning MTAG analysis...
MTAG will use the Z column for analyses.
Read in Trait 1 summary statistics (10311290 SNPs) from .\preprocessed sumstats MTAG\hypothyroidism_preproc_sumsats.txt ...
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
snpid:  Variant ID (e.g., rs number)
n:      Sample size
a1:     a1, interpreted as ref allele for signed sumstat.
pval:   p-Value
a2:     a2, interpreted as non-ref allele for signed sumstat.
z:      Directional summary statistic as specified by --signed-sumstats.

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Read 10311290 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
10311290 SNPs remain.
Removed 1 SNPs with duplicated rs numbers (10311289 SNPs remain).
Removed 0 SNPs with N < 0.0 (10311289 SNPs remain).
Median value of SIGNED_SUMSTAT was -0.000506329113924, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 1.506
Lambda GC = 1.213
Max chi^2 = 902.258
22927 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Tue Jan 10 17:46:08 2023
Total time elapsed: 3.0m:18.65s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 1 complete. SNPs remaining:     10311290
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Trait 1: Dropped 1 SNPs for duplicate values in the "snp_name" column
Read in Trait 2 summary statistics (8614797 SNPs) from .\preprocessed sumstats MTAG\anemia_preproc_sumsats.txt ...
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
snpid:  Variant ID (e.g., rs number)
n:      Sample size
a1:     a1, interpreted as ref allele for signed sumstat.
pval:   p-Value
a2:     a2, interpreted as non-ref allele for signed sumstat.
z:      Directional summary statistic as specified by --signed-sumstats.

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
Read 8614797 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
8614797 SNPs remain.
Removed 8809 SNPs with duplicated rs numbers (8605988 SNPs remain).
Removed 0 SNPs with N < 0.0 (8605988 SNPs remain).
Median value of SIGNED_SUMSTAT was -0.00618662056108, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 1.031
Lambda GC = 1.02
Max chi^2 = 69.224
117 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Tue Jan 10 17:48:04 2023
Total time elapsed: 1.0m:21.39s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 2 complete. SNPs remaining:     8614797
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Trait 2: Dropped 8809 SNPs for duplicate values in the "snp_name" column
Dropped 1553169 SNPs due to strand ambiguity, 8758120 SNPs remain in intersection after merging trait1
Dropped 3030 SNPs due to inconsistent allele pairs from phenotype 2. 6632555 SNPs remain.
Flipped the signs of of 2956677 SNPs to make them consistent with the effect allele orderings of the first trait.
Dropped 0 SNPs due to strand ambiguity, 6632555 SNPs remain in intersection after merging trait2
... Merge of GWAS summary statistics complete. Number of SNPs:   6632555
Using 6632555 SNPs to estimate Omega (0 SNPs excluded due to strand ambiguity)
Estimating sigma..
Checking for positive definiteness ..
Sigma hat:
[[1.068 0.06 ]
 [0.06  1.   ]]
Mean chi^2 of SNPs used to estimate Omega is low for some SNPsMTAG may not perform well in this situation.
Beginning estimation of Omega ...
Using GMM estimator of Omega ..
Checking for positive definiteness ..
Completed estimation of Omega ...
Beginning MTAG calculations...
 ... Completed MTAG calculations.
Writing Phenotype 1 to file ...
Writing Phenotype 2 to file ...

Summary of MTAG results:
------------------------
  Trait                 # SNPs used  N (max)  N (mean)  GWAS mean chi^2  MTAG mean chi^2  GWAS equiv. (max) N
1  ...proc_sumsats.txt  6632555      183579   183579    1.523            1.524            184203
2  ...proc_sumsats.txt  6632555        6190     6190    1.026            1.126             30099

Estimated Omega:
[[3.040e-06 1.871e-06]
 [1.871e-06 4.173e-06]]

(Correlation):
[[1.    0.525]
 [0.525 1.   ]]

Estimated Sigma:
[[1.068 0.06 ]
 [0.06  1.   ]]

(Correlation):
[[1.    0.058]
 [0.058 1.   ]]

MTAG weight factors: (average across SNPs)
[1.004 2.002]

**Comment by paturley** [comment]
Hi Chloe,

The explanation that you quote is more of an intuitive heuristic and a
precise explanation of what MTAG does. The "Estimated Omega" matrix found
in the log file is the estimated variance-covariance matrix of the marginal
effect of the SNPs included in the MTAG analysis. The "Correlation" matrix
below that is the correlation matrix corresponding to the
variance-covariance matrix. So the off-diagonal entry is the correlation of
the marginal effects, which is a potential definition of "genetic
correlation" though it's different than the definition of genetic
correlation used in LD score regression (which is the correlation of causal
effects) or in twin studies (which is the correlation of the additive
genetic factors). All of these measures of genetic correlation are closely
related though and (except in extreme circumstances) they will be very
close to each other. You could verify this by passing your summary
statistics into LDSC and seeing if you get something in the ballpark of
0.525.

The other correlation matrix is the correlation of the estimation error
between the two traits. This should be zero if there is no sample overlap.
Given that your estimate is 0.058, my guess is that your two traits are
phenotypically correlated and perhaps have a small amount of sample
overlap. (Though that number is small enough that it may just be noise.)

In terms of why the two mean chi2 numbers differ, the number reported in
the section where MTAG is munging each set of summary statistic separately,
it is the mean chi2 statistics for all SNPs that survive single trait QC.
The number in the summary table is the mean chi2 statistic for the SNPs
that are ultimately used in MTAG, which is the intersection of the sets of
SNPs for each trait passed into MTAG. So if there are many SNPs that are in
one traits' sumstats but not the other, these two mean chi2 numbers can
differ.

Best,
Patrick
