### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by sreeashwinas** [JonJala/mtag#181]
Hello

Could you please provide the **wiki page** with the tutorials for running the analysis containing sample data format and result format.
Would be greatly appreciated.

Regards

Ashwin

**Comment by paturley** [comment]
Sure. Here is a link. The different tutorials can be found in the right sidebar. https://github.com/JonJala/mtag/wiki

**Comment by sreeashwinas** [comment]
Thank you so much for the quick response.

Regards

Ashwin
