### ISSUE TITLE
Can I make a MTAG for a disease and its classification from a same cohort?

### ISSUE THREAD

**Issue by dqq0404** [JonJala/mtag#207]
Hi,
Can I make a MTAG for a disease and its classification from a same cohort? For example,I have three GWAS Summary data,one is age-related macular degeneration (whether dry or wet), the remaining two are dry and wet,and all of them are from a same cohort.I think the sample sizes of these three will overlap a lot.

**Comment by paturley** [comment]
As described in the paper, sample overlap should not be a problem for MTAG.

Best,
Patrick
